adapter_name_or_path: saves/Qwen2.5-7B-Instruct/lora/train_2026-05-01-06-48-46
cutoff_len: 2048
dataset_dir: data
ddp_timeout: 180000000
do_predict: true
eval_dataset: security_dataset_test
finetuning_type: lora
flash_attn: auto
max_new_tokens: 2048
max_samples: 100000
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
output_dir: saves/Qwen2.5-7B-Instruct/lora/eval_sec_1
per_device_eval_batch_size: 4
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.1
template: qwen
top_p: 0.7
trust_remote_code: true
